### ISSUE TITLE
MapBox token is invalid

### ISSUE THREAD

**Issue by thoroc** [arank/marauders-map#10]
Just installed this by curiousity only to find it broken. Pulled up the dev console in chrome and ffound the MapBox token [to be broken](https://a.tiles.mapbox.com/v4/arankhanna.m3ankjj3.json?access_token=pk.eyJ1IjoiYXJhbmtoYW5uYSIsImEiOiJjYWYxOTcwYTI4ZTNhNDA5NTdlMzFjMDQ0NWM3OThjMSJ9.j6OVr_W3jAAdxusZ5qLXlg&secure). The response json is the following:
```
{"message":"Not Authorized - Invalid Token"}
```

**Comment by yassine-khachlek** [comment]
Hi, i have tested this plugin and it work well, note that you should create your own account in mapbox.com, then create a map and change the the accessToken & map_id in src/fb/content.js with your own.

**Comment by boxstore** [comment]
user 0 point 0
how to fix
