### ISSUE TITLE
Question about map background layer

### ISSUE THREAD

**Issue by dvorapa** [arank/marauders-map#8]
Could be offtopic, but I hope somebody will help me. If I go to facebook.com/messages, map opens automatically in down-left corner on a position somewhere in Atlantic ocean with default zoom. But I live on the other side of the world and all my friends are less than 50 km far from me. How could I set default position and zoom in Mapbox map? (I tried some possibilities and googled a lot, but without any result)

BTW thank you, the author of this extension, for this awesome work. I know it looks like it will die in a few days, but I totally love this 2nd dimension of the text location notification in fb chat (which nobody reads at all I think)...

**Comment by xrisk** [comment]
Unrelated but is it working for you ? I’m getting nulls co-ord values for all requests :/

**Comment by dvorapa** [comment]
I don't know, first I've solved issues in css in my own fork, second I'm trying to fix this issue. On this side of the world is now deep night, so nobody is online to see, where he is or where he was...

**Comment by xrisk** [comment]
It doesn’t matter if people are online or not. The way the app works — if you scroll up to an old message that was sent using messenger with location turned on, it should turn up on the map. But currently it’s not, even with location turned on. I just confirmed it by having a friend send me a message with location turned on. So either Facebook’s changed the location retrieval mechanism, or they’ve put a system-wide blanket on location services.

Marauder’s Map is now broken.

**Comment by dvorapa** [comment]
Ah-ha, okay, sorry for my confusedness. So it probably died, so early... But if it'd start working in a future (or the author would find any solution), how could I set map prefferences I'd asked before.

**Comment by necov** [comment]
I just got the map to work, and now has an issue with "0 Users and 0 Points". Did facebook already break this extension?

**Comment by xrisk** [comment]
The map will come, locations will not turn up.

**Comment by necov** [comment]
So yes, it is broken?

**Comment by xrisk** [comment]
Yes. What have I written above? -_-

**Comment by xrisk** [comment]
I quote — “Marauder’s Map is now broken"

**Comment by xrisk** [comment]
@dvorapa line 181 of the js file

**Comment by dvorapa** [comment]
@xrisk Thank you! I've searched on Mapbox, but I didn't know, it is set in code.
